### ISSUE TITLE
Understanding columns in `g4mp2_data.json.gz`

### ISSUE THREAD

**Issue by newalexander** [globus-labs/solvation-energy-ml#4]
Hello!

Thank you for publishing the code and data for your paper. Can you clarify what the `smiles_0` and `smiles_1` columns correspond to in your full dataset (https://github.com/globus-labs/solvation-energy-ml/blob/master/data/output/g4mp2_data.json.gz)?

From what I can tell,  the `xyz` column is what is ingested by the MPNN model (https://github.com/globus-labs/solvation-energy-ml/blob/master/jcesr_ml/keras.py#L181), and the `smiles_0` and `smiles_1` columns are not used. Is this correct? Thanks!

**Comment by WardLT** [comment]
Hi @newalexander, thanks for reaching out!

SMILES 0 is what was used to create the molecule by the QM9 team and SMILES 1 is the molecule structure after relaxation (which I believe will include stereochemistry). See [the QM9 paper](https://www.nature.com/articles/sdata201422) for more details.

We actually use the `smiles_0` column when running the model, though any SMILES string will work. See here: https://github.com/globus-labs/solvation-energy-ml/blob/master/mpnn-gpu/train_models.py#L80

Pardon the refences to `xyz` in the `keras.py` file. That is legacy code from a previous paper, and I've learned valuable lessons about starting from a blank slate when I start a new project 😬
